# Kind cluster configuration
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ml-benchmark
nodes:
- role: control-plane
  extraPortMappings:
  # BentoML service
  - containerPort: 30300
    hostPort: 3000
    protocol: TCP
  # FastAPI service
  - containerPort: 30800
    hostPort: 8000
    protocol: TCP
  # Locust web UI
  - containerPort: 30089
    hostPort: 8089
    protocol: TCP
